---
#
# Default Ansible YAML
#  
- name: download redis source
  get_url: url=http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz 
           dest=/tmp/redis-{{ redis_version }}.tar.gz

- name: unarchive redis source
  command: tar -xzf /tmp/redis-{{ redis_version }}.tar.gz chdir=/tmp creates=/tmp/redis-{{ redis_version }}

- name: build redis
  command: make chdir=/tmp/redis-{{ redis_version }} creates=/tmp/redis-{{ redis_version }}/src/redis-server
  
- name: install redis
  command: make install chdir=/tmp/redis-{{ redis_version }} creates=/usr/local/bin/redis-server
